package:
  name: telingo
  version: "1.0"

source:
  git_rev: wip
  git_url: https://github.com/rkaminsk/telingo.git

requirements:
  build:
    - clingo
    - python
    - setuptools
  run:
    - clingo
    - python

build:
  script:
    - python setup.py test
    - python setup.py install

about:
  home:  https://potassco.org/
  license: MIT
  summary: A solver for temporal logic programs.
  description: Telingo is a solver for temporal logic programs.
  license_file: LICENSE.md

